# Generated by Django 4.2.23 on 2026-01-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('smartphones', 'Smartphones'), ('laptops', 'Laptops'), ('tablets', 'Tablets'), ('audio', 'Audio'), ('cameras', 'Cameras'), ('wearables', 'Wearables'), ('gaming', 'Gaming'), ('accessories', 'Accessories')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('imageSrc', models.URLField(max_length=500)),
                ('is_bestseller', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
