# Generated by Django 4.2.23 on 2026-03-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadget1', '0002_populate_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('smartphones', 'Smartphones'), ('laptops', 'Laptops'), ('tablets', 'Tablets'), ('audio', 'Audio'), ('cameras', 'Cameras'), ('wearables', 'Wearables'), ('gaming', 'Gaming'), ('accessories', 'Accessories'), ('grocery', 'Groceries'), ('footwear', 'Footwear')], max_length=50),
        ),
    ]
