# Generated by Django 4.2.23 on 2026-03-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadget1', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('smartphones', 'Smartphones'), ('laptops', 'Laptops'), ('accessories', 'Accessories'), ('grocery', 'Groceries'), ('footwear', 'Footwear')], max_length=50),
        ),
    ]
