# Generated by Django 4.2.23 on 2026-03-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadget1', '0004_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, help_text='Enter features as bullet points, one per line')),
                ('button_text', models.CharField(blank=True, default='View Deals', max_length=100)),
                ('button_link', models.URLField(blank=True, default='/shop/', max_length=500)),
                ('active', models.BooleanField(default=True, help_text='Show on home page?')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Promotions',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
