# Generated by Django 4.2.23 on 2026-03-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadget1', '0005_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imageSrc',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
