# Generated by Django 4.2.23 on 2026-04-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadget1', '0006_product_image_alter_product_imagesrc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('topic', models.CharField(choices=[('general', 'General enquiry'), ('order', 'Order support'), ('delivery', 'Delivery question'), ('quote', 'Quote request')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('smartphones', 'Smartphones'), ('laptops', 'Laptops'), ('tablets', 'Tablets'), ('audio', 'Audio'), ('cameras', 'Cameras'), ('wearables', 'Wearables'), ('gaming', 'Gaming'), ('accessories', 'Accessories'), ('grocery', 'Groceries'), ('footwear', 'Footwear')], max_length=50),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='button_link',
            field=models.CharField(blank=True, default='/shop/', max_length=500),
        ),
    ]
